name: dumbproxy
version: '1.18.0'
summary: Dumbest HTTP proxy ever.
description: >
  Dumbest HTTP proxy ever. See documentation for details:
  https://github.com/SenseUnit/dumbproxy/blob/master/README.md

confinement: strict
base: core18

parts:
  dumbproxy:
    plugin: go
    go-importpath: github.com/SenseUnit/dumbproxy
    source: .
    build-packages:
      - gcc

apps:
  dumbproxy:
    command: bin/dumbproxy
    plugs:
      - network
      - network-bind
