name: dumbproxy
version: '1.5.0'
summary: Dumbiest HTTP proxy ever.
description: >
  Dumbiest HTTP proxy ever. See documentation for details:
  https://github.com/Snawoot/dumbproxy/blob/master/README.md

confinement: strict
base: core18

parts:
  dumbproxy:
    plugin: go
    go-importpath: github.com/Snawoot/dumbproxy
    source: .
    build-packages:
      - gcc

apps:
  dumbproxy:
    command: bin/dumbproxy
    plugs:
      - network
      - network-bind
